# Generated by Django 4.2.1 on 2023-06-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=255)),
                ('CategoryDescription', models.CharField(max_length=255, null=True)),
                ('CategoryImage', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('PhoneNumber', models.CharField(max_length=20, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('City', models.CharField(max_length=20, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('PostalCode', models.CharField(max_length=20, null=True)),
                ('Password', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('Description', models.TextField(null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Image', models.TextField(null=True)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CoffeeShop.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.CharField(max_length=20)),
                ('TotalAmount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('PaymentType', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('CustomerOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='CoffeeShop.customers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=20)),
                ('ItemNotes', models.CharField(default=None, max_length=255)),
                ('ItemPrice', models.CharField(default=None, max_length=255)),
                ('ItemDiscount', models.CharField(default=None, max_length=3)),
                ('ItemTotal', models.DecimalField(decimal_places=0, max_digits=20)),
                ('ItemStatus', models.CharField(default=None, max_length=20)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CoffeeShop.orders')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CoffeeShop.products')),
            ],
        ),
    ]
