# Generated by Django 4.2.1 on 2023-06-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='ItemNotes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
